# GH actions.
name: Build Docker Images

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  Build:
    strategy:
      matrix:
        platform:
          - cpu
          - cu121
          - cu122

    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Reclaim disk space
      run: |
        df -h
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/.ghcup
        df -h
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        set -eux
        cd docker
        docker build -t package-${{ matrix.platform }} -f Dockerfile.package-${{ matrix.platform }} .
    - name: Upload to GHCR
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        set -eux
        docker tag package-${{ matrix.platform }} ghcr.io/${{ github.actor }}/package-${{ matrix.platform }}:latest
        docker push ghcr.io/${{ github.actor }}/package-${{ matrix.platform }}:latest